version: '3.1'
services:
    rest-api-test:
        image: rest-api-test:latest
        networks:
            - backend
        environment:
            - REST_API_DB_HOST=database
        depends_on:
          - "database"
    database:
        image: mongo:latest
        networks:
            - backend

networks:
    backend:
